### PR TITLE
quick_sort algorithm #1

### PR DESCRIPTION
**Pull request by satya-vinay**
#1 Added a new sorting algorithm.

### CODE REVIEW

**Comment by kvaluruk** [comment]
@satya-vinay not to be too enforcing, but this should go into `c/quick_sort.cpp`

**Comment by satya-vinay** [comment]
@kvaluruk oh sorry, I will edit it.

**Comment by satya-vinay** [comment]
is this okay now?

**Comment by kvaluruk** [comment]
Awesome!
It has been merged. Cheers!

**Pull request merged**
