### PR TITLE
Minimum spanning tree

### PR DESCRIPTION
**Pull request by thegauravtiwari**

### CODE REVIEW

**Comment by thegauravtiwari** [comment]
#1

**Comment by kvaluruk** [comment]
@thegauravtiwari Please remove the `.DS_Store` binary files.

**Comment by thegauravtiwari** [comment]
@kvaluruk done

**Comment by kvaluruk** [comment]
@thegauravtiwari If the file has been committed before being added to the `.gitignore`, it needs to be removed using `git rm --cached <file>`.

[https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore](url)

**Comment by kvaluruk** [comment]
One `.DS_Store` still remains.

**Comment by thegauravtiwari** [comment]
There's is none

**Comment by kvaluruk** [comment]
`java/.DS_Store` :stuck_out_tongue:

**Comment by thegauravtiwari** [comment]
Done

**Comment by kvaluruk** [comment]
Thanks! Merged.

**Pull request merged**
