### PR TITLE
Added the stack data structure written in Python 3.5

### PR DESCRIPTION
**Pull request by arsenal-2004**

### CODE REVIEW

**Comment by arsenal-2004** [comment]
For issue no #21

**Comment by kvaluruk** [comment]
Thanks @arsenal-2004 

Quick suggestion, rebasing is generally preferred over pulling since it creates a separate commit for merging.

**Comment by kvaluruk** [comment]
Merged, thanks!

**Comment by arsenal-2004** [comment]
Thanks for your suggestion. I was not sure about the use of rebasing, but now I understood how to use it.

**Pull request merged**
