### PR TITLE
Added Breadth-First-Search in Java Algorithms

### PR DESCRIPTION
**Pull request by Aniket144**

### CODE REVIEW

**Comment by qoh** [comment]
> Bread-First-Search

Now that's something people can agree upon. :smirk: :bread:

**Comment by Aniket144** [comment]
Oops! Is there a way to edit the Commit Message?

**Comment by qoh** [comment]
@Aniket144 In a local clone of your fork, run `git commit --amend`, which will let you recreate the commit with a different message. Then use `git push --force` to overwrite the history on GitHub.

**Comment by kvaluruk** [comment]
@qoh Awesome guidance! Thanks

**Pull request merged**
